<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Sveriges Kommuner och Landsting licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->		
<wsdl:definitions name='CreateFormInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:tjsr='urn:riv:infrastructure:eservicesupply:forminteraction:CreateFormResponder:2' xmlns:tjsi='urn:riv:infrastructure:eservicesupply:forminteraction:CreateForm:2' xmlns:tns='urn:riv:infrastructure:eservicesupply:forminteraction:CreateForm:2:rivtabp21' targetNamespace='urn:riv:infrastructure:eservicesupply:forminteraction:CreateForm:2:rivtabp21' xmlns:itr='urn:riv:itintegration:registry:1'>
  <xs:annotation>
    <xs:documentation>
			 Tjänsteinteraktionens namn: CreateFormInteraction
			 Beskrivning: 
			   Skapa formulär. Tjänsten används för att skapa och starta ett formulär.
			 Revisioner: 
			 Tjänstedomän: infrastructure:eservicesupply:forminteraction
			 Tjänsteinteraktionstyp: Fråga-Svar
			 WS-profil: RIVTABP21
			 Förvaltas av: Sveriges Kommuner och Landsting
			 Författare: Marco de Luca
			 </xs:documentation>
  </xs:annotation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:infrastructure:eservicesupply:forminteraction:CreateForm:2:rivtabp21'>
      <xs:import schemaLocation='CreateFormResponder_2.0.xsd' namespace='urn:riv:infrastructure:eservicesupply:forminteraction:CreateFormResponder:2' />
      <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='CreateFormRequest'>
    <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
      <wsdl:documentation>Logical address description</wsdl:documentation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:CreateForm' />
  </wsdl:message>
  <wsdl:message name='CreateFormResponse'>
    <wsdl:part name='parameters' element='tjsr:CreateFormResponse' />
  </wsdl:message>
  <wsdl:portType name='CreateFormResponderInterface'>
    <wsdl:operation name='CreateForm'>
      <wsdl:input message='tns:CreateFormRequest' />
      <wsdl:output message='tns:CreateFormResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='CreateFormResponderBinding' type='tns:CreateFormResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='CreateForm'>
      <soap:operation soapAction='urn:riv:infrastructure:eservicesupply:forminteraction:CreateFormResponder:2:CreateForm' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:CreateFormRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='CreateFormResponderService'>
    <wsdl:port name='CreateFormResponderPort' binding='tns:CreateFormResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>